[workspace]
members = [
    "eth_test_parser",
    "evm_test_runner",
    "common",
]

[workspace.dependencies]
plonky2_evm = { path = "../plonky2/evm" }
plonky2 = { path = "../plonky2/plonky2" }


[profile.release]
lto = "fat"
codegen-units = 1


